# Generated by Django 4.2.6 on 2023-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Currency name IS03')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Currency description')),
            ],
        ),
    ]
